name: RestorerID
channels:
  - pytorch
  - defaults
dependencies:
  - numpy=1.23.1
  - pip=20.3.3
  - python=3.9.20
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - torchvision=0.13.1
  - pip:
    - absl-py==2.1.0
    - accelerate==1.0.1
    - addict==2.4.0
    - aiohappyeyeballs==2.4.3
    - aiohttp==3.10.10
    - aiosignal==1.3.1
    - albumentations==1.3.0
    - altair==5.4.1
    - antlr4-python3-runtime==4.8
    - asttokens==2.4.1
    - async-timeout==4.0.3
    - attrs==24.2.0
    - bitsandbytes==0.44.1
    - blinker==1.8.2
    - braceexpand==0.1.7
    - cachetools==5.5.0
    - cfgv==3.4.0
    - click==8.1.7
    - colorama==0.4.6
    - coloredlogs==15.0.1
    - comm==0.2.2
    - contourpy==1.3.0
    - cycler==0.12.1
    - cython==3.0.11
    - decorator==5.1.1
    - distlib==0.3.9
    - docker-pycreds==0.4.0
    - easydict==1.13
    - einops==0.3.0
    - exceptiongroup==1.2.2
    - executing==2.1.0
    - facexlib==0.3.0
    - filelock==3.16.1
    - filterpy==1.4.5
    - flatbuffers==24.3.25
    - fonttools==4.54.1
    - frozenlist==1.5.0
    - fsspec==2024.10.0
    - ftfy==6.3.1
    - future==1.0.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - grpcio==1.67.1
    - huggingface-hub==0.26.2
    - humanfriendly==10.0
    - icecream==2.1.3
    - identify==2.6.1
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - importlib-metadata==8.5.0
    - importlib-resources==6.4.5
    - iniconfig==2.0.0
    - insightface==0.7.3
    - invisible-watermark==0.2.0
    - ipython==8.18.1
    - ipywidgets==8.1.5
    - jedi==0.19.1
    - jinja2==3.1.4
    - joblib==1.4.2
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - jupyterlab-widgets==3.0.13
    - kiwisolver==1.4.7
    - kornia==0.6.0
    - lazy-loader==0.4
    - llvmlite==0.43.0
    - lmdb==1.5.1
    - lpips==0.1.4
    - markdown==3.7
    - markdown-it-py==3.0.0
    - markupsafe==3.0.2
    - matplotlib==3.9.2
    - matplotlib-inline==0.1.7
    - mdurl==0.1.2
    - mpmath==1.3.0
    - multidict==6.1.0
    - narwhals==1.11.1
    - networkx==3.2.1
    - nodeenv==1.9.1
    - numba==0.60.0
    - omegaconf==2.1.1
    - onnx==1.17.0
    - onnxruntime-gpu==1.15.0
    - open-clip-torch==2.0.2
    - openai-clip==1.0.1
    - opencv-python==4.6.0.66
    - opencv-python-headless==4.10.0.84
    - packaging==24.1
    - pandas==2.2.3
    - parso==0.8.4
    - pexpect==4.9.0
    - pillow==11.0.0
    - platformdirs==4.3.6
    - pluggy==1.5.0
    - pre-commit==4.0.1
    - prettytable==3.11.0
    - prompt-toolkit==3.0.48
    - propcache==0.2.0
    - protobuf==3.20.3
    - psutil==6.1.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pyarrow==18.0.0
    - pydeck==0.9.1
    - pydeprecate==0.3.1
    - pyfacer==0.0.4
    - pygments==2.18.0
    - pyiqa==0.1.13
    - pympler==1.1
    - pyparsing==3.2.0
    - pytest==8.3.3
    - python-dateutil==2.9.0
    - pytorch-lightning==1.5.0
    - pytz==2024.2
    - pywavelets==1.6.0
    - pyyaml==6.0.2
    - qudida==0.0.4
    - referencing==0.35.1
    - regex==2024.9.11
    - rich==13.9.3
    - rpds-py==0.20.0
    - safetensors==0.4.5
    - scikit-image==0.20.0
    - scikit-learn==1.5.2
    - scipy==1.9.1
    - semver==3.0.2
    - sentencepiece==0.2.0
    - sentry-sdk==2.17.0
    - setproctitle==1.3.3
    - smmap==5.0.1
    - stack-data==0.6.3
    - streamlit==1.12.1
    - streamlit-drawable-canvas==0.8.0
    - sympy==1.13.3
    - tensorboard==2.18.0
    - tensorboard-data-server==0.7.2
    - test-tube==0.7.5
    - threadpoolctl==3.5.0
    - tifffile==2024.8.30
    - timm==1.0.11
    - tokenizers==0.15.2
    - toml==0.10.2
    - tomli==2.0.2
    - torchmetrics==0.6.0
    - tornado==6.4.1
    - tqdm==4.66.6
    - traitlets==5.14.3
    - transformers==4.37.2
    - triton==3.1.0
    - tzdata==2024.2
    - tzlocal==5.2
    - validators==0.34.0
    - virtualenv==20.27.1
    - wandb==0.18.5
    - watchdog==5.0.3
    - wcwidth==0.2.13
    - webdataset==0.2.5
    - werkzeug==3.0.6
    - widgetsnbextension==4.0.13
    - yapf==0.40.2
    - yarl==1.17.0
    - zipp==3.20.2
